// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ufD-rmQtCSthQAava4Oq6hDkt8qKmE4',
    appId: '1:66955648953:web:5e93896b41bf30aebe6068',
    messagingSenderId: '66955648953',
    projectId: 'contaction-44c5a',
    authDomain: 'contaction-44c5a.firebaseapp.com',
    storageBucket: 'contaction-44c5a.appspot.com',
    measurementId: 'G-3WX9FRRBDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuql_g2HSZzk09O_8IUmsfmkCTTTC4TtQ',
    appId: '1:66955648953:android:46f6feb0fd46af9abe6068',
    messagingSenderId: '66955648953',
    projectId: 'contaction-44c5a',
    storageBucket: 'contaction-44c5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDsgNkwntwzhEMWdd5U6I1GmYwpVdDkaU',
    appId: '1:66955648953:ios:84494ac5f3598685be6068',
    messagingSenderId: '66955648953',
    projectId: 'contaction-44c5a',
    storageBucket: 'contaction-44c5a.appspot.com',
    iosBundleId: 'com.example.finaleProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDsgNkwntwzhEMWdd5U6I1GmYwpVdDkaU',
    appId: '1:66955648953:ios:6b65e12bac6dbb3abe6068',
    messagingSenderId: '66955648953',
    projectId: 'contaction-44c5a',
    storageBucket: 'contaction-44c5a.appspot.com',
    iosBundleId: 'com.example.finaleProj.RunnerTests',
  );
}
